name: text2
description: Plugin to markup text effectively and efficiently in Flutter.
version: 0.0.1
homepage: https://github.com/rey-xi/text2/tree/master
repository: https://github.com/rey-xi/text2

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
